### ISSUE TITLE
Lcd.off and Lcd.on problem

### ISSUE THREAD

**Issue by crouse12** [microbit-foundation/micropython-microbit-v2#12]
I found that python editor beta 2.1.0-beta.6 for microbit v2 has a bug for led screen.
When I use the following python program, led screen on microbit v2 has some errors.
Can anyone help me?
PS. python editor Editor Version: 2.0.1 for microbit v1 does not have this bug

![image](https://user-images.githubusercontent.com/25700616/98490453-85b55d00-226c-11eb-9ca2-c10e30698414.png)

**Comment by dpgeorge** [comment]
Thanks for the report.  The issue is that pin10 is connected to the display and `display.on()` does not fully reset the display, so the `pin10.write_analog(0)` has a side effect of leaving the last column all lit up.

@microbit-carlos would we expect `uBit.display.enable()` to fully reset the display?

**Comment by microbit-carlos** [comment]
Yes, I think it should: https://github.com/lancaster-university/codal-microbit-v2/issues/21

pin10 is also a display pin on V1, and this doesn't seem to be an issue in V1.

**Comment by dpgeorge** [comment]
I tested this with the latest build using the latest CODAL and it is fixed.
